openapi: 3.1.0
info:
  title: Safety Assistant API
  version: "0.1.0"
servers:
  - url: https://my-safety-api.vercel.app
paths:
  /api/gpt:
    post:
      operationId: safetyAssistant
      summary: Custom GPT entrypoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [function_name, arguments]
              properties:
                function_name:
                  type: string
                  enum: [search_safety_law]
                arguments:
                  type: object
                  additionalProperties: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [status]
                properties:
                  status: { type: string, enum: [OK, ERROR] }
                  answer:
                    type: object
                    properties:
                      law_name: { type: string }
                      law_id: { type: string }
                      source_url: { type: string, format: uri }
                      effective_date: { type: string }
                  checklist: { type: array, items: { type: string } }
                  limitations: { type: array, items: { type: string } }
